// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    public partial class ActivityTag
    {
        [Key]
        public int id { get; set; }
        public int tagId { get; set; }
        public int activityId { get; set; }

        [ForeignKey("activityId")]
        [InverseProperty("ActivityTag")]
        public virtual Activity activity { get; set; }
    }
}