// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    public partial class Activity
    {
        [Key]
        public int id { get; set; }
        public int userid { get; set; }
        [Required]
        [StringLength(50)]
        public string title { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public int type { get; set; }
        [Required]
        [StringLength(100)]
        public string location { get; set; }
        [Required]
        [StringLength(100)]
        public string introduction { get; set; }
        public int maxnumber { get; set; }
        public int curnumber { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime starttime { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime endtime { get; set; }
    }
}