// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    public partial class ApplyActivity
    {
        public int activity_id { get; set; }
        public int userid { get; set; }
        [Key]
        public int id { get; set; }
        public int status { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime applytime { get; set; }
    }
}