// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    public partial class Payment
    {
        [Key]
        public int activityId { get; set; }
        [Column("payment")]
        public double payment1 { get; set; }
        public int type { get; set; }

        [ForeignKey("activityId")]
        [InverseProperty("Payment")]
        public virtual Activity activity { get; set; }
    }
}