// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    public partial class UserInformation
    {
        [Key]
        public int id { get; set; }
        [StringLength(10)]
        public string sex { get; set; }
        public int? age { get; set; }
        [StringLength(50)]
        public string hobby { get; set; }
        [StringLength(100)]
        public string brief { get; set; }
        public double? x { get; set; }
        public double? y { get; set; }
        [StringLength(100)]
        public string location { get; set; }
    }
}