// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    [Keyless]
    public partial class View_ApplyStatus
    {
        public int activity_id { get; set; }
        public int userid { get; set; }
        public int status { get; set; }
        [Column(TypeName = "date")]
        public DateTime applytime { get; set; }
        [Required]
        [StringLength(50)]
        public string state { get; set; }
        public int id { get; set; }
    }
}