// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    [Keyless]
    public partial class View_ApplyActivity
    {
        public int activity_id { get; set; }
        public int userid { get; set; }
        public int id { get; set; }
        public int status { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime applytime { get; set; }
        [Required]
        [StringLength(50)]
        public string title { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public int typeId { get; set; }
        [Required]
        [StringLength(100)]
        public string location { get; set; }
        public int maxnumber { get; set; }
        [Required]
        [StringLength(100)]
        public string introduction { get; set; }
        public int curnumber { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime starttime { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime endtime { get; set; }
        public int CreatorId { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatorName { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatorImage { get; set; }
        [Required]
        [StringLength(50)]
        public string username { get; set; }
        [Required]
        [StringLength(50)]
        public string userImage { get; set; }
        [Required]
        [StringLength(50)]
        public string type { get; set; }
    }
}