// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YouAndI_Entity
{
    [Keyless]
    public partial class View_StarActivity
    {
        public int createUerId { get; set; }
        [Required]
        [StringLength(50)]
        public string title { get; set; }
        public double x { get; set; }
        [Required]
        [StringLength(50)]
        public string createUserName { get; set; }
        [Required]
        [StringLength(50)]
        public string type { get; set; }
        public int typeID { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime endtime { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime starttime { get; set; }
        public int curnumber { get; set; }
        public int maxnumber { get; set; }
        [Required]
        [StringLength(100)]
        public string introduction { get; set; }
        [Required]
        [StringLength(100)]
        public string location { get; set; }
        [Required]
        [StringLength(50)]
        public string image { get; set; }
        public double y { get; set; }
        public int activityId { get; set; }
        public int userId { get; set; }
        public int id { get; set; }
    }
}